<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Models\BaseModel;
use Auth;
class Page extends BaseModel
{
    use HasFactory;
    protected $fillable = ['name','slug','description','view','layout','has_custom_view','display_to_menu','is_active','is_delete','is_home_page'];
    protected $table = 'pages';

    public $rules = [
        'name' => 'required',
        'slug' => 'required',
        'view' =>  'required',
        'description' => 'required',
        'layout' => 'required',
        'display_to_menu' => 'required|min:0|max:1',
        'is_home_page' => 'required|min:0|max:1',
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('active_pages', function (Builder $builder) {
            $user = Auth::user();
            if(isset($user) && !$user->hasRole('admin')){
                $builder->where('pages.is_delete', '=', 0);
            }else{
                $builder->where('pages.is_delete', '=', 0)->where('pages.is_active','=',1);
            }
           
        });
    }

    public function setSlugAttribute($slug)
    {

        if(isset($this->id)){
            $category = self::where('slug',$slug)->where('id','!=',$this->id)->first();
            $this->attributes['slug'] = $slug.'-'.((int)$this->id);
            return true;
        }
        $category = self::where('slug',$slug)->first();
        if(isset($category)){
            $this->attributes['slug'] = $slug.'-'.((int)$category->id+1);
            return true;
        }
        $this->attributes['slug'] = $slug;
        return true;
    }
}
